# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApiposturePro < Formula
  desc "Professional API security inspection tool for Go applications"
  homepage "https://apiposture.dev"
  version "1.0.11"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.11_darwin_amd64.tar.gz"
      sha256 "14cfb5c23d4f7ff6460297f1931be5d3fc6e149259ff89ce80ca120379d7587e"

      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.11_darwin_arm64.tar.gz"
      sha256 "a1f4d71e05d5a554998e79916ec238e18cc22e85be086c65b35fc7ad2937402c"

      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.11_linux_amd64.tar.gz"
      sha256 "e05b1f8f54caff8df01710c2dc66ff1b3ff1bbd5d6efc4542dad6aa21ad8bc26"
      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.11_linux_arm64.tar.gz"
      sha256 "408f676907af1ce82341fc6a495c064475d5f6a48968b09b4c2ce84c5091868a"
      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
  end

  test do
    system "#{bin}/apiposture-pro", "version"
  end
end
