# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApiposturePro < Formula
  desc "Professional API security inspection tool for Go applications"
  homepage "https://apiposture.dev"
  version "1.0.7"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.7_darwin_amd64.tar.gz"
      sha256 "f9096fd24a31f9062e8940e28583c2de55bd018ee2e41ba0c321b57c6b35f73a"

      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.7_darwin_arm64.tar.gz"
      sha256 "4eb634b8cef1dd560129e498dc535134b05f14131b1b505cad0bb01e48a6820a"

      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.7_linux_amd64.tar.gz"
      sha256 "e692d7c7f5098f2a8519ab0d4cc1a45c4656c5807c003eb4ab658bd4d8589df5"
      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://www.apiposture.com/releases/apiposture-pro_1.0.7_linux_arm64.tar.gz"
      sha256 "bff4a093c16ab054afae50f9b96154fd2d7b1c9b947d0f778e795794aa15a589"
      define_method(:install) do
        bin.install "apiposture-pro"
      end
    end
  end

  test do
    system "#{bin}/apiposture-pro", "version"
  end
end
